version: '3.1'

services:

# mongoDB service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

# mongo-express service
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

#  nodeJS service
  nodejs:
      image: "node:latest"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=dev
      volumes:
        - ./server:/home/node/app
      ports:
        - "3000:3000"
        - "3001:3000"
      command: "npm run dev"
